# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxRealmDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxRealmDemo
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ContactsWrapper'
  pod 'IBAnimatable'
end
